ACD: 50 #Association Dummy Cost
NHDC: 2 #New Hypothesis Dummy Cost
MINPROPAGATE: 15 #NUMBER AFTER WHICH A TRACK IS ACCEPTED
MAXMISSED: 15 #NUMBER AFTER WHICH A TRACK IS DELETED
DT: 0.5 #INITIAL DT OF THE KALMAN FILTER
